name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt-get install libsdl2-2.0 libsdl2-dev libsdl2-image-dev
    - name: make
      run: make
